WIP
TimeForPlanet/time-planet pull request #229
Opened 2020-10-05 09:16 UTC by lucyjosef

Pour regarder si j'ai oublié qqchose pour faire fonctinoner la pagination

2020-10-05 09:59 UTC, BlancFrancois commented on app/controllers/investors_controller.rb
> +    page_nb = params[:page].nil? ? 1 : params[:page]
T'es sûre qu'il y a besoin de `params[:page].nil? ? 1 : params[:page]` 

Dans les contents on mets juste `.page(params[:page])` à la fin de la requête.

2020-10-12 11:23 UTC, lucyjosef commented on app/views/investors/index.html.erb
> +          <% if @investors.any? %>
bah celle ci je l'avait rajouté parce que j'avais cette erreur `undefined method `total_pages' for #<ActiveRecord::Relation []>`

2020-10-12 12:04 UTC, lucyjosef commented on app/views/investors/index.html.erb
> +                    <div class="InvestorsCards-left--badgeContent">
et si je lui passe une double classe genre class="InvestorsCards-flex" c'est ok ? parce qu'en fait c'est juste pour cet attribut là que j'avais fait ça

2020-10-12 12:53 UTC, BlancFrancois commented on app/views/investors/index.html.erb
> +          <% if @investors.any? %>
Je comprends pas où est-ce que tu appelles total_pages ?

2020-10-12 12:53 UTC, BlancFrancois commented on spec/factories/accomplishments.rb
> +FactoryBot.define do
Si on ne les complète pas les factories et les fichiers de tests sans test. On supprime tout ça.

2020-10-12 12:53 UTC, BlancFrancois commented on app/controllers/investors_controller.rb
> +  end
Je crois que t'as supprimé la route qui correspondait donc tu peux supprimer la méthode maintenant.

2020-10-12 12:53 UTC, BlancFrancois commented on app/views/investors/index.html.erb
> +                        <div class="InvestorsCard-body--badges"></div>
Du coup ce que j'ai peut-être  pas fini de dire tout à l'heure c'est qu'ici ce que tu devrais utiliser ce n'est pas un modifier mais plutôt faire `InvestorCard-badges` tout simplement.

2020-10-12 14:47 UTC, dvkch commented on app/controllers/investors_controller.rb
> +  def filter_investors(params, record)
C'est une des parties qu'on fera dans un concern, afin de pouvoir gérer le mix entre les Company et les User

2020-10-12 15:22 UTC, dvkch requested changes
Coucou ! J'ai fais quelques retours plutot sur la partie back, hesite pas à commenter ou m'envoyer un message sur Slack si j'ai mis des choses qui te paraissent fausses ou que tu ne comprends pas

2020-10-12 15:22 UTC, dvkch commented on app/models/concerns/investor_search.rb
> +      User.send("full_text_search_#{I18n.locale}", term)
L'intéret d'avoir cette méthode dans `content_search.rb` est de pouvoir faire une recherche qui utilise `body_i18n`, `title_i18n` et `slug_i18n`, mais uniquement en utilisant la version de ces attributs pour la langue actuelle (`I18n.locale`). Dans ce cas on a donc bien la définition des scopes `:full_text_search_fr, :full_text_search_en, etc`, et une méthode qui permet d'utiliser le bon : `self.full_text_search(term)`

Dans la mesure où les attributs d'un user ne contiennent pas de colonne traduite via Mobility tu as bien défini un seul `pg_search_scope`, tu peux donc enlever la méthode `self.full_text_search(term)` et rendre le `pg_search_scope` public. Tu peux meme utiliser `pg_search_scope :full_text_search`, pour abbréger le `.to_sym` qui n'est plus nécessaire.

Je te recommande d'ajouter un test dessus pour vérifier que tout marche bien

2020-10-12 15:22 UTC, dvkch commented on app/models/concerns/investor_search.rb
> +module InvestorSearch
Je pense que `UserSearch` serai plus adapté. La méthode de recherche ne sera pas la meme pour les User et les Company. Tu pourras aussi créer ton équivalent `CompanySearch` et les tester indépendamment

2020-10-12 15:22 UTC, dvkch commented on app/controllers/investors_controller.rb
> +  def search
Cette route n'est pas necessaire à mon avis, tu peux tout rassembler dans l'index et filtrer les éléments retournés si  `params[:search].present?`

2020-10-12 15:22 UTC, dvkch commented on config/routes.rb
> +      get "/", to: "investors#search", as: "investors_search"
cf commentaire sur `InvestorsController#search`, tu pourras enlever cette route une fois que tu auras mis en place la recherche à l'interieur meme de l'index

2020-10-12 15:22 UTC, dvkch commented on db/migrate/20200929112455_create_accomplishments.rb
> +      t.references :shareholder, index: true, null: false, foreign_key: {to_table: :users}
je crois qu'il ne faut pas préciser la table associée, et ignorer l'attribut `foreign_key`. Cet attribut permet à Postgres de t'empecher de supprimer un record s'il est encore référencé par un autre record, ici c'est problématique puisque le record référence peut être dans la table users ou companies. On se passera donc de cette sécurité de Postgres et on s'en remettra à Rails pour éviter de tomber dans un état incohérent. Je laisse quand meme @BlancFrancois donner son avis

2020-10-12 15:22 UTC, dvkch commented on config/locales/investors.fr.yml
> +        field: "current_job"
@BlancFrancois comment est-ce que ces traductions sont elles censées etre gérées ? Est-ce qu'elles ne devraient pas etre en base ? Si elles restent dans `fr.yml` alors il manque leur équivalent anglaise

2020-11-24 15:04 UTC, closed without merging