Feature: invest models + specs
TimeForPlanet/time-planet pull request #244
Opened 2020-10-15 10:02 UTC by lucyjosef

2020-10-15 12:44 UTC, BlancFrancois commented on app/models/accomplishment.rb
> +  belongs_to :user, polymorphic: true, class_name: "User", foreign_key: :shareholder_id, optional: true
Ce serait pas mal, comme sur master, on a déjà le modèle `Companies` que les accomplishments puissent belong_to Company aussi et qu'il  y ait des tests qui montrent que la relation polymorphic fonctionne bien. Je pense que pour un truc comme ça, ce serait bien que ce soit pas des should_matchers mais qu'on ait des vrai tests unitaires qui montrent que peut à la fois associé des users et à la fois associer des companies.

2020-10-19 15:09 UTC, dvkch requested changes
Tout me semble complet et bien testé, je t'ai quand meme mis quelques remarques que j'aimerai bien que tu regardes avant que j'autorise la PR, mais rien de majeur

2020-10-19 15:09 UTC, dvkch commented on spec/factories/accomplishments.rb
> +      shareholder_type { "Company" }
est-ce que spécifier `shareholder_type` est nécessaire ? les tests ne passent pas sans ?

2020-10-19 15:09 UTC, dvkch commented on spec/models/accomplishment_spec.rb
> +      accomplishment = FactoryBot.create(:accomplishment, badge_id: badge.id, shareholder_id: user.id)
je serai plutot d'avis de passer `badge: badge, shareholder: user` et laisser Rails s'occuper des ids. je pense que ça devrait aussi enlever le besoin de passer `shareholder_type` dans le FactoryBot de `accomplishment`

2020-10-19 15:09 UTC, dvkch commented on spec/models/accomplishment_spec.rb
> +      expect(accomplishment.shareholder_type).to eq("User")
ce test aura d'ailleurs encore plus de sens quand tu auras enlevé l'assignation dans le FactoryBot, ça nous permet de vérifier que n'importe quelle assignation d'un user à un accomplishment mets bien à jour l'id et le type dans l'accomplishment sans qu'on n'ai à s'en préoccuper

2020-10-19 15:09 UTC, dvkch commented on spec/models/badge_spec.rb
> +    end
cet ensemble de test me parait complet, cependant quelques remarques : 

- ca serai cool d'avoir des commentaires qui explique un peu ce que tu cherches à tester, à savoir qu'un meme badge peut etre associé à plusieurs accomplishments, l'un associé à un User, l'autre associer à une Company, et que tu le confirmes en vérifiant company.badges.first == user.badges.first. 

- meme remarque sur le passage d'ID à la création des accomplishments.

- je pense que les deux lignes d'association ne devraient pas etre necessaires (`user.accomplishments << [...]`), normalement tes accomplishments sont déjà créés en étant associés à leur user ou company, donc tu devrais directement avec `company.badges.first == badge`. peut etre que celà necessite un `reload` sur `user` & `company` par contre

2020-10-19 15:54 UTC, BlancFrancois commented on spec/models/badge_spec.rb
> +    end
Je prends le train, en route. Je suis globalement d'accord avec tous les commentaires de Stan. Sauf sur le fait de mettre des commentaires. Je pense Stan que ça fait un peu suite à notre discussion sur ta MR concernant les tests. 
D'après ma faible expérience, à de rares exceptions près, les commentaires ne sont pas une très bonne idée. A mon sens il vaut mieux avoir une description de test qui exprime bien ce qu'on test, quite à faire plusieurs tests avec le même scénario, mais avec des expectations différentes et du coup une description différente qui exprime bien pour chaque test ce qu'on cherche à tester.
Mais les commentaires, on oubli souvent de les mettre à jour, quand on modifie le code qui les concerne et on finit avec des commentaires qui n'ont plus rien à voir avec le code qui est censé aller avec.

2020-10-19 16:17 UTC, lucyjosef commented on spec/factories/accomplishments.rb
> +      shareholder_type { "Company" }
si je les enlève il me donne cette erreur : ActiveRecord::RecordInvalid: La validation a échoué : doit exister Shareholder

2020-10-19 16:24 UTC, lucyjosef commented on spec/models/accomplishment_spec.rb
> +      accomplishment = FactoryBot.create(:accomplishment, badge_id: badge.id, shareholder_id: user.id)
oui effectivement ça passe pour ce test là, même sans préciser le shareholder_type, c'est les tests des badges qui n'aiment pas

2020-10-19 16:38 UTC, lucyjosef commented on spec/models/badge_spec.rb
> +    end
je viens de capter qu'en fait j'ai même pas besoin de lui faire cette attribution `company.badges.first == badge` puisque qu'on déclare les accomplishments avec leur id, ça gère l'attribution des badges
du coup en supprimant ces deux lignes, le test passe bien

2020-10-20 11:09 UTC, dvkch commented on spec/factories/accomplishments.rb
> +      shareholder_type { "Company" }
@lucyjosef je viens de faire le test en enlevant le `shareholder_type` ici et les associations par ID dans `badges_spec` et ça fonctionne. La transformation faite dans `badges_spec` : 

```
       FactoryBot.create(:accomplishment, badge: badge, shareholder: user)
```

L'idée est que si tu donnes à Rails juste un ID il ne connait pas le type et il ne peut pas valider l'existence du modèle associé, par contre si tu lui passes une instance complete il peut sans soucis remplir les deux attributs `shareholder_id` et `shareholder_type`

2020-10-20 13:31 UTC, lucyjosef commented on spec/factories/accomplishments.rb
> +      shareholder_type { "Company" }
aaaah yes ! du coup oui les tests passent bien c'est cool et au moins on test bien la relation :)

2020-10-20 13:32 UTC, lucyjosef commented on spec/models/badge_spec.rb
> +    end
et du coup j'ai retiré les commentaires ici

2020-10-20 16:04 UTC, dvkch approved these changes
Tout bon pour moi. Petite note cependant, je pense que certains noms de "it" dans les tests peuvent etre clarifiés, mais je ne considèrerai pas ça bloquant, je laisse @BlancFrancois confirmer :)

2020-10-20 17:12 UTC, BlancFrancois approved these changes

2020-10-20 17:12 UTC, BlancFrancois commented on db/migrate/20201016113017_add_accomplishable_to_accomplishments.rb
> +end
Si je dois faire juste une dernière remarques c'est que je ne comprends pas pourquoi on a deux migrations pour créer un seul modèle. Mais on peut merger comme ça c'est pas très grave.

2020-10-21 09:33 UTC, merged